# Site settings
title: Saulo Jacques
email: saulojacques@protonmail.com
description: "Ecologia | Tecnologias Livres | Ciência Cidadã"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://smjacques.github.io" # the base hostname & protocol for your site
github_username:  smjacques

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jemoji
